# =============================================================================
# load_data.R
# Load processed TMAO data into R
#
# Usage (RStudio):
#   Open this file in RStudio, then run with Ctrl+Shift+S (Source)
#   or run sections with Ctrl+Enter.
#
# Working directory must be the project root (TMAO_data_analysis/).
#   Session > Set Working Directory > To Project Directory
# =============================================================================

# -----------------------------------------------------------------------------
# 0. Working directory check
# -----------------------------------------------------------------------------
if (!file.exists("data/production/processed/samplesheet.csv")) {
  stop(
    "Processed data not found.\n",
    "Set the working directory to the project root:\n",
    "  Session > Set Working Directory > To Project Directory"
  )
}

# -----------------------------------------------------------------------------
# 1. Load processed data
# -----------------------------------------------------------------------------
samplesheet <- read.csv(
  "data/production/processed/samplesheet.csv",
  stringsAsFactors = FALSE
)

feat_meta <- read.csv(
  "data/production/processed/feature_metadata.csv",
  stringsAsFactors = FALSE
)

feat_mat <- read.csv(
  "data/production/processed/feature_matrix.csv",
  row.names     = 1,
  check.names   = FALSE,
  stringsAsFactors = FALSE
)

cat("=== Data loaded ===\n")
cat(sprintf("samplesheet : %d samples x %d columns\n",
            nrow(samplesheet), ncol(samplesheet)))
cat(sprintf("feat_meta   : %d features x %d columns\n",
            nrow(feat_meta), ncol(feat_meta)))
cat(sprintf("feat_mat    : %d features x %d samples\n",
            nrow(feat_mat), ncol(feat_mat)))

# -----------------------------------------------------------------------------
# 1b. Merge MS-FINDER rank-1 annotations into feat_meta (if available)
#
#   Source : data/production/processed/feature_metadata_msfinder_2090.csv
#            (generated by src/python/annotate_unknown_msfinder.py)
#
#   For "Unknown" features that MS-FINDER successfully annotated, the following
#   columns are added to feat_meta (rank-1 / best-score candidate only):
#     MSFINDER_structure, MSFINDER_total_score, MSFINDER_formula,
#     MSFINDER_ontology, MSFINDER_inchikey, MSFINDER_smiles, MSFINDER_databases
#   A logical helper column MSFINDER_annotated is also set (TRUE / FALSE).
#
#   feat_meta_msfinder : full table including all candidate ranks (for reference)
# -----------------------------------------------------------------------------
MSFINDER_COLS <- c("MSFINDER_structure", "MSFINDER_total_score",
                   "MSFINDER_formula",   "MSFINDER_ontology",
                   "MSFINDER_inchikey",  "MSFINDER_smiles",
                   "MSFINDER_databases")
MSFINDER_CSV <- "data/production/processed/feature_metadata_msfinder_2090.csv"

if (file.exists(MSFINDER_CSV)) {
  feat_meta_msfinder <- read.csv(MSFINDER_CSV, stringsAsFactors = FALSE)

  # Extract rank-1 candidates only (one row per Alignment_ID)
  msfinder_rank1 <- feat_meta_msfinder[
    !is.na(feat_meta_msfinder$MSFINDER_rank) & feat_meta_msfinder$MSFINDER_rank == 1L,
    c("Alignment_ID", MSFINDER_COLS)
  ]

  # Merge into feat_meta
  feat_meta <- merge(feat_meta, msfinder_rank1, by = "Alignment_ID", all.x = TRUE)
  feat_meta$MSFINDER_annotated <- !is.na(feat_meta$MSFINDER_structure)

  n_annotated <- sum(feat_meta$MSFINDER_annotated, na.rm = TRUE)
  cat(sprintf("feat_meta + MSFINDER    : %d Unknown features newly annotated\n",
              n_annotated))
} else {
  # File not found — add empty columns so downstream scripts don't error
  for (col in c(MSFINDER_COLS, "MSFINDER_annotated")) {
    feat_meta[[col]] <- NA
  }
  feat_meta_msfinder <- NULL
  cat("MS-FINDER output not found — MSFINDER columns set to NA.\n")
  cat(sprintf("  Expected: %s\n", MSFINDER_CSV))
}

# -----------------------------------------------------------------------------
# 2. Convenience subsets of samplesheet
# -----------------------------------------------------------------------------

# Biological samples only (excludes rerun, BLK, QC)
bio <- samplesheet[samplesheet$type == "biological", ]

# Biological + rerun
bio_all <- samplesheet[samplesheet$type %in% c("biological", "rerun"), ]

# QC samples
qc  <- samplesheet[samplesheet$type == "QC", ]

# BLK samples
blk <- samplesheet[samplesheet$type == "BLK", ]

cat(sprintf("\nbio (biological only) : %d samples\n", nrow(bio)))
cat(sprintf("bio_all (+ rerun)     : %d samples\n", nrow(bio_all)))
cat(sprintf("qc                    : %d samples\n", nrow(qc)))
cat(sprintf("blk                   : %d samples\n", nrow(blk)))

# -----------------------------------------------------------------------------
# 3. Helper: extract a numeric sub-matrix
#    Usage: mat <- get_mat(bio$label)
# -----------------------------------------------------------------------------
get_mat <- function(labels) {
  cols <- intersect(labels, colnames(feat_mat))
  feat_mat[, cols, drop = FALSE]
}

# =============================================================================
# Example operations (run line by line as needed)
# =============================================================================

# --- A. Average over technical replicates (same Subject x Timepoint) ---------
#
# avg_mat: rows = features, cols = "{Subject}-{Timepoint}"
#
# avg_mat <- sapply(
#   split(bio$label, paste(bio$Subject, bio$Timepoint, sep = "-")),
#   function(cols) rowMeans(get_mat(cols), na.rm = TRUE)
# )
# dim(avg_mat)  # 17670 features x 240 Subject-Timepoint combinations

# --- B. All samples at a specific timepoint -----------------------------------
#
# tp1_meta <- bio[bio$Timepoint == 1, ]
# tp1_mat  <- get_mat(tp1_meta$label)   # 17670 features x 40 subjects (x3 repeats)

# --- C. Time series for one subject (6 timepoints) ---------------------------
#
# s001_meta <- bio[bio$Subject == "001", ]
# s001_meta <- s001_meta[order(s001_meta$Timepoint, s001_meta$Repeat), ]
# s001_mat  <- get_mat(s001_meta$label)

# --- D. Split by period: early (T1-3) vs late (T4-6) -------------------------
#
# early_meta <- bio[bio$period == "early", ]
# late_meta  <- bio[bio$period == "late",  ]
# early_mat  <- get_mat(early_meta$label)
# late_mat   <- get_mat(late_meta$label)

# --- E. Intensity of a single feature across all biological samples ----------
#
# feature_id <- 0   # Alignment_ID (integer)
# row_idx    <- which(feat_meta$Alignment_ID == feature_id)
# vals       <- as.numeric(feat_mat[row_idx, bio$label])
# plot(vals, main = feat_meta$Metabolite_name[row_idx])
